# Generated by Django 4.1 on 2023-07-19 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.SmallIntegerField(choices=[(0, '技术类'), (1, '技术类'), (2, '运营类'), (3, '产品类'), (4, 'iOS 开发工程师'), (5, '安卓开发工程师'), (6, '音视频开发工程师')], verbose_name='职位类别')),
                ('job_name', models.CharField(max_length=255, verbose_name='职位名称')),
                ('job_city', models.SmallIntegerField(choices=[(0, '上海'), (1, '广州'), (2, '北京'), (3, '深圳')], verbose_name='岗位城市')),
                ('job_responsibility', models.CharField(max_length=1024, verbose_name='职位职责')),
                ('job_requirements', models.CharField(max_length=255, verbose_name='任职要求')),
                ('created_date', models.DateTimeField(verbose_name='创建日期')),
                ('modified_date', models.DateTimeField(verbose_name='修改时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
        ),
    ]
