# Generated by Django 4.2.3 on 2023-07-23 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_name',
            field=models.CharField(max_length=1024, verbose_name='职位名称'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_requirements',
            field=models.TextField(max_length=255, verbose_name='任职要求'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_responsibility',
            field=models.TextField(max_length=1024, verbose_name='职位职责'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.SmallIntegerField(choices=[(0, '技术类'), (1, '测试类'), (2, '运营类'), (3, '产品类'), (4, 'iOS 开发工程师'), (5, '安卓开发工程师'), (6, '音视频开发工程师')], verbose_name='职位类别'),
        ),
        migrations.AlterField(
            model_name='job',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间'),
        ),
    ]
