# Generated by Django 4.2.3 on 2023-07-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='first_interviewer',
            field=models.CharField(blank=True, max_length=256, verbose_name='面试官'),
        ),
    ]
