# Generated by Django 4.1 on 2023-08-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_candidate_first_interviewer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name': '应聘者', 'verbose_name_plural': '所有应聘者'},
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, max_length=135, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='last_editor',
            field=models.CharField(blank=True, max_length=256, verbose_name='最后编辑者'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='user_name',
            field=models.CharField(max_length=135, verbose_name='姓名'),
        ),
    ]
